DROP TABLE IF EXISTS "ordercustomization" CASCADE;
DROP TABLE IF EXISTS "orderitem" CASCADE;
DROP TABLE IF EXISTS "foodcustomization" CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS "food" CASCADE;
DROP TABLE IF EXISTS "foodcatalogue" CASCADE;
