// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: food.sql

package db

import (
	"context"
)

const createFood = `-- name: CreateFood :one
INSERT INTO food (
    name,
    description,
    price,
    category_id
) VALUES (
             $1,
             $2,
             $3,
             $4
         ) RETURNING id, name, description, price, category_id
`

type CreateFoodParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int32  `json:"price"`
	CategoryID  int32  `json:"category_id"`
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRowContext(ctx, createFood,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.CategoryID,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CategoryID,
	)
	return i, err
}

const getFood = `-- name: GetFood :one
SELECT id, name, description, price, category_id FROM food
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFood(ctx context.Context, id int32) (Food, error) {
	row := q.db.QueryRowContext(ctx, getFood, id)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CategoryID,
	)
	return i, err
}

const listFood = `-- name: ListFood :many
SELECT id, name, description, price, category_id FROM food
WHERE category_id = $1
ORDER BY id
`

func (q *Queries) ListFood(ctx context.Context, categoryID int32) ([]Food, error) {
	rows, err := q.db.QueryContext(ctx, listFood, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Food
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFood = `-- name: UpdateFood :one
UPDATE food
SET name = $2, description = $3, price = $4, category_id = $5
WHERE id = $1
RETURNING id, name, description, price, category_id
`

type UpdateFoodParams struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int32  `json:"price"`
	CategoryID  int32  `json:"category_id"`
}

func (q *Queries) UpdateFood(ctx context.Context, arg UpdateFoodParams) (Food, error) {
	row := q.db.QueryRowContext(ctx, updateFood,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.CategoryID,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CategoryID,
	)
	return i, err
}
