// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Food struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int32  `json:"price"`
	CategoryID  int32  `json:"category_id"`
}

type Foodcatalogue struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Foodcustomization struct {
	ID                int32  `json:"id"`
	FoodID            int32  `json:"food_id"`
	CustomizationType string `json:"customization_type"`
	Value             string `json:"value"`
}

type Order struct {
	ID         int32  `json:"id"`
	OrderDate  string `json:"order_date"`
	TotalPrice int32  `json:"total_price"`
	Status     string `json:"status"`
}

type Ordercustomization struct {
	OrderItemID         int32 `json:"order_item_id"`
	FoodCustomizationID int32 `json:"food_customization_id"`
}

type Orderitem struct {
	ID        int32 `json:"id"`
	OrderID   int32 `json:"order_id"`
	FoodID    int32 `json:"food_id"`
	Quantity  int32 `json:"quantity"`
	ItemPrice int32 `json:"item_price"`
}
